backend:
  name: git-gateway
  branch: main # 你的主分支名称

media_folder: "images" # 上传图片存放的文件夹
public_folder: "/images" # 图片访问路径

collections:
  - name: "global"
    label: "全局设置"
    files:
      - name: "general"
        label: "网站基本信息"
        file: "_data/site.yml" # 我们将把数据存在这里
        fields:
          - { label: "网站标题", name: "site_title", widget: "string" }
          - { label: "Logo图片", name: "logo", widget: "image" }

  - name: "team"
    label: "团队成员/招聘"
    folder: "_team"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "姓名/职位", name: "name", widget: "string" }
      - { label: "照片", name: "photo", widget: "image" }
      - { label: "简介", name: "bio", widget: "text" }
